
backend:
  name: github
  repo: cesko-digital/blog
  base_url: https://oauth.cesko.digital
  auth_endpoint: /auth
  open_authoring: true
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
site_url: "https://blog.cesko.digital"
collections:
  - label: "Posts"
    label_singular: "Post"
    name: "posts"
    folder: "content/posts"
    path: '{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Author"
        name: "author"
        widget: "select"
        options: ["zoul", "radja", "jakub", "eva", "vjirovsky", "jana", "marketaz",
          "teryii", "urbant", "hrudka", "katka", "dana", "zaneta", "iva", "bara",
          "alena", "lukas", "tt", "kaku", "martina", "gabi", "lenkab", "rona",
          "lvanous", "horm", "zu"]
        required: true
      - label: "Cover"
        name: "cover"
        widget: "string"
        required: true
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD-hh-mm"
        required: true
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true
      - label: "Description"
        name: "description"
        widget: "string"
        required: true
      - label: "Language"
        name: "lang"
        widget: "select"
        options: ["cs", "en"]
        default: "cs"
      - label: "Text"
        name: "body"
        widget: "markdown"
